### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by johnclary**
Hi devs,

This repo is ready for your code review. Would someone review the contents of `/meters` and spend some time with the `txn_history.py` script?

A copy of the environment file is in 1pass, and readme should step you through the works. The dev environment is enabled by default.

### CODE REVIEW

**Comment by johnclary** [comment]
ah, it just occurred to me to use [cerberus](https://docs.python-cerberus.org/en/stable/) for schema validation, as we are elsewhere (h/t @sergiogcx). i will add that to the todo list.

**Review by sergiogcx — APPROVED** [review]
Looks good! 🚢 💯  I love this part: `new_row = {k: v for k, v in row.items() if k.upper() not in FORBIDDEN_KEYS}` I very much love working with the cerberus library, I think you will too.

**Review by chiaberry — APPROVED** [review]
looks great! some sticky keyboard typos in the docstrings but that's all I could see that would need any attention ⌨️

**Review by frankhereford — APPROVED** [review]
This works great!

Everything operates just like it's described. Docker image built w/o problems and I was able to download data specified by dates and see them uploaded to S3 - all as documented. 

It did take me a second to notice that when you run it without start and end dates, you do get "yesterday", but as the README notes, it's **UTC yesterday.** This only to say that it's doing exactly what it should be, but the README might benefit from a sentence that warns a user who runs it without date arguments that they can expect two files to be uploaded to S3, including one for today. I could also see file name collisions happening on that S3 bucket if a user thinks they can cron this to run daily and at any time other than UTC midnight. I'm probably overthinking this. 

I also pushed a branch, based on jc-update-docs, called flh-typos that corrects a handful of typos, but nothing that impacted the execution of the program.

**Comment by johnclary** [comment]
thanks y'all!

@frankhereford i appreciate that feedback and for fixing my typos. i'll update the docs. i'll add a note about the number of files uploaded and considerations around name collisions. in this case, we're actually banking on name collisions. e.g. if you query for today's transactions today and again tomorrow, tomorrow's results will be more complete and should replace today's version.

**Comment by mateoclarke** [comment]
One suggestion. Make a template env file with null values and put in the README where the env file can be found instead of just in this PR description.

**Pull request merged**
